export const ENV = {
	VTEX_ACCOUNT: "VTEX_ACCOUNT",
	VTEX_ENV: "VTEX_ENV",
	VTEX_APP_KEY: "VTEX_APP_KEY",
	VTEX_APP_TOKEN: "VTEX_APP_TOKEN",
};

export const API = {
	TIMEOUT_IN_MILLISECONDS: 5000,
	MAX_REQUESTS_PER_MILLISECONDS: 5,
	SEARCH_PAGINATION_THRESHOLD: 2500,
	SEARCH_PAGINATION_MAX_INTERVAL: 50,
};
